import sys
import os
import json
from curl_cffi import requests

# Ensure project root is in path
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from lib.common.executor import run_request
from lib.device_profile import DEFAULT_PROFILE

# Reference Data Index: 155
# Method: POST
#
# Original Headers (Comparison):
# ------------------------------
# {
#     'content-type': 'application/json; charset=utf-8',
#     'content-length': '30255',
#     'accept-encoding': 'gzip',
#     'user-agent': 'okhttp/4.9.3'
# }
# ------------------------------

def run(session: requests.Session):
    url = "https://ljc.coupang.com/api/v2/bulksubmit?appCode=coupang&market=KR"
    method = "POST"
    
    headers = {
        'content-type': 'application/json; charset=utf-8',
        'content-length': '30255',
        'accept-encoding': 'gzip',
        'user-agent': 'okhttp/4.9.3'
    }
    
    body = [
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.054+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 18359,
                'schemaVersion': 1
            },
            'data': {
                'domain': 'sdp',
                'logCategory': 'impression',
                'logType': 'impression',
                'pageName': 'sdp',
                'eventName': 'sdp_atf_shipping_info_impression',
                'sdpVisitKey': 'fyuk5pnr11rkb1z4qh',
                'productId': 9024146312,
                'itemId': 26462223018,
                'vendorItemId': 93437504336,
                'pddMessage': '화요일 1/13 도착 예정',
                'isFreeShipping3pBadge': True,
                'isShipsToday3pBadge': False,
                'isFreeReturn3pBadge': False,
                'hasDeliveryFee': 'false',
                'isDeliveryFeeConditional': False,
                'hasSellerName': True,
                'hasShipperName': True
            },
            'extra': {}
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.075+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 15987,
                'schemaVersion': 1
            },
            'data': {
                'domain': 'srp',
                'logCategory': 'view',
                'logType': 'modal',
                'pageName': 'srp',
                'eventName': 'page_leave',
                'pvid': '70757900'
            },
            'extra': {}
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.076+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 17062,
                'schemaVersion': 1
            },
            'data': {
                'domain': 'cmg',
                'logCategory': 'system',
                'logType': 'performance',
                'pageName': None,
                'eventName': 'image_enlargement_logging',
                'eventId': 'b35cb0a0-ed78-11f0-8b76-d328a895e0de',
                'definition': '657x657q90trim',
                'compress': 'true',
                'ratio': '0.99847794'
            },
            'extra': {}
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.095+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 14057,
                'schemaVersion': 2
            },
            'data': {
                'domain': 'search',
                'logCategory': 'impression',
                'logType': 'impression',
                'pageName': 'SearchFragment',
                'eventName': 'image_loads',
                'networkType': 'wifi',
                'fileSizeList': '693888,803648,814784,4624,827776',
                'imageResolutionList': '417x416,433x464,439x464,34x34,464x446',
                'imageUrlList': 'https://thumbnail9.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/5e47/8d2e8bc32200b474bdf439f8fe02705fe1fd5e2d45b4a4bf3496a3a8f9e7.png.webp,https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/image_audit/prod/1c6b2b3e-795b-48af-9b52-01993a5595e6_fixing_v2.png.webp,https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/3b3a/29bcfec71c7f96c93b580e2df31da837e3779be4f7c74f953bd1d0535197.jpg.webp,https://image.coupangcdn.com/image/coupang/rds/icon/xxhdpi/rds_icon_similar_outline1702461081753.png,https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/d5bb/1922703ddb30b2e92bdce03dcb318285547c6da0829d86c2cc9198b0dba7.png.webp',
                'resultList': 'SUCCESS,SUCCESS,SUCCESS,SUCCESS,SUCCESS',
                'itemIdList': 'null,27087300150,26462223016,null,27087300159',
                'productIdList': 'null,9183773210,9024146312,null,9183773210',
                'vendorItemIdList': 'null,94055536143,93437504341,null,94055536145',
                'sdpVisitKey': None,
                'searchId': '0797993d22350',
                'q': '호박식혜 달빛',
                'cacheTypeList': 'DATA_DISK_CACHE,DATA_DISK_CACHE,MEMORY_CACHE,MEMORY_CACHE,DATA_DISK_CACHE',
                'sourceType': 'search_dco-ads,search_pup,search_pup,search_pup,search_pup',
                'imageDurationList': '25,138,0,0,28',
                'rawByteSizeList': '64940,18216,-1,-1,22314'
            },
            'extra': {
                'rankList': 'null,6,2,null,3'
            }
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.096+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 137,
                'schemaVersion': 12
            },
            'data': {
                'domain': 'tti',
                'logCategory': 'system',
                'logType': 'performance',
                'pageName': 'srp',
                'eventName': 'tti-logger',
                'platformType': 'native',
                'tti': 540,
                'bounced': False,
                'screenType': 'searchHome',
                'viewCreateTime': 7,
                'apiResponseTime': 175,
                'viewBindingTime': 1,
                'imageLoadingTime': 0,
                'networkState': 'wifi',
                'carrier': 'unknown',
                'webViewVersion': '131.0.6778.260',
                'ixid': '00014a5f-3364-99cc-a426-e1b671c81782',
                'async': None,
                'serverTime': None,
                'domReady': None,
                'applicationId': None,
                'serverProcessingTime': None,
                'serverFetchingTime': None,
                'responseSize': 2339,
                'akamaiToGatewayServiceTime': 6,
                'internalProcessingTime': 32,
                'transferTime': 143,
                'imageCount': 0,
                'prepareApiTime': 25,
                'prepareImageTime': 0,
                'maxImageSize': None,
                'averageImageSize': None,
                'parsingTime': 228,
                'pageVersion': None,
                'cdn': 'envoy',
                'viewUpdateTime': 0,
                'gatewayProcessingTime': None,
                'responseTransferTime': 2,
                'apiBeforeFetchingTime': 0,
                'apiAfterFetchingTime': 0
            },
            'extra': {
                'api': '[{"key":"searchHome","time":175,"parse":228,"dispatch":1,"binding":1,"client_request_to_cdn":67,"client_request_to_gw":73,"gw_response_to_client":68,"response_transfer_time":2,"content_length":2339,"unzipped_size":21694}]',
                'image': '[]',
                'total': '430',
                'categoryDepth': '',
                'campaignId': '',
                'signal': -1,
                'viewUpdateTime': 0,
                'prepareApiTime': 25,
                'prepareImageTime': 0,
                'maxImageUrl': '',
                'isorganic': 'true'
            }
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.098+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 137,
                'schemaVersion': 12
            },
            'data': {
                'domain': 'tti',
                'logCategory': 'system',
                'logType': 'performance',
                'pageName': 'srp',
                'eventName': 'tti-logger',
                'platformType': 'native',
                'tti': 0,
                'bounced': False,
                'screenType': 'searchResult',
                'viewCreateTime': 36,
                'apiResponseTime': 0,
                'viewBindingTime': -9,
                'imageLoadingTime': 0,
                'networkState': 'wifi',
                'carrier': 'unknown',
                'webViewVersion': '131.0.6778.260',
                'ixid': '00014a5f-2f77-d840-47d7-bc3457fe0367',
                'async': None,
                'serverTime': None,
                'domReady': None,
                'applicationId': None,
                'serverProcessingTime': None,
                'serverFetchingTime': None,
                'responseSize': 0,
                'akamaiToGatewayServiceTime': None,
                'internalProcessingTime': None,
                'transferTime': None,
                'imageCount': 0,
                'prepareApiTime': 0,
                'prepareImageTime': 0,
                'maxImageSize': None,
                'averageImageSize': None,
                'parsingTime': 0,
                'pageVersion': None,
                'cdn': 'none',
                'viewUpdateTime': 0,
                'gatewayProcessingTime': None,
                'responseTransferTime': 0,
                'apiBeforeFetchingTime': 0,
                'apiAfterFetchingTime': 0
            },
            'extra': {
                'api': '[]',
                'image': '[]',
                'total': '27',
                'categoryDepth': '',
                'campaignId': '',
                'signal': -1,
                'viewUpdateTime': 0,
                'prepareApiTime': 0,
                'prepareImageTime': 0,
                'maxImageUrl': '',
                'isorganic': 'true',
                'datasize': '611296'
            }
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.100+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 137,
                'schemaVersion': 12
            },
            'data': {
                'domain': 'tti',
                'logCategory': 'system',
                'logType': 'performance',
                'pageName': 'srp_comp',
                'eventName': 'tti-logger',
                'platformType': 'native',
                'tti': 1342,
                'bounced': False,
                'screenType': 'searchResult',
                'viewCreateTime': 36,
                'apiResponseTime': 855,
                'viewBindingTime': 40,
                'imageLoadingTime': 142,
                'networkState': 'wifi',
                'carrier': 'unknown',
                'webViewVersion': '131.0.6778.260',
                'ixid': '00014a5f-2f79-23fb-e384-abdc292008d4',
                'async': None,
                'serverTime': None,
                'domReady': None,
                'applicationId': None,
                'serverProcessingTime': 644,
                'serverFetchingTime': 558,
                'responseSize': 0,
                'akamaiToGatewayServiceTime': 6,
                'internalProcessingTime': 684,
                'transferTime': 171,
                'imageCount': 2,
                'prepareApiTime': 43,
                'prepareImageTime': 1243,
                'maxImageSize': 59910,
                'averageImageSize': 39063,
                'parsingTime': 169,
                'pageVersion': None,
                'cdn': 'envoy',
                'viewUpdateTime': 126,
                'gatewayProcessingTime': 40,
                'responseTransferTime': 6,
                'apiBeforeFetchingTime': 0,
                'apiAfterFetchingTime': 0
            },
            'extra': {
                'api': '[{"key":"searchResult","time":855,"parse":169,"dispatch":8,"binding":40,"client_request_to_cdn":66,"client_request_to_gw":72,"gw_response_to_client":92,"response_transfer_time":6,"content_length":0,"unzipped_size":611296}]',
                'image': '[{"key":"LegoSquareImage","time":138,"url":"https:\\/\\/thumbnail.coupangcdn.com\\/thumbnails\\/remote\\/657x657q90trim\\/image\\/vendor_inventory\\/image_audit\\/prod\\/1c6b2b3e-795b-48af-9b52-01993a5595e6_fixing_v2.png.webp","preload":"NONE","image_loading_end":"363271968","image_size":"18216","image_decoding":"22","image_loading_start":"363271830","after_decoding":"114","image_fetching":"0","before_fetching":"1","cacheType":"DATA_DISK_CACHE"},{"key":"LegoSquareImage","time":84,"url":"https:\\/\\/thumbnail.coupangcdn.com\\/thumbnails\\/remote\\/657x657q90trim\\/image\\/vendor_inventory\\/3b3a\\/29bcfec71c7f96c93b580e2df31da837e3779be4f7c74f953bd1d0535197.jpg.webp","preload":"NONE","image_loading_end":"363271972","image_size":"59910","image_decoding":"29","image_loading_start":"363271888","after_decoding":"53","image_fetching":"1","before_fetching":"1","cacheType":"DATA_DISK_CACHE"}]',
                'total': '1117',
                'categoryDepth': '',
                'campaignId': '',
                'signal': -1,
                'viewUpdateTime': 126,
                'prepareApiTime': 43,
                'prepareImageTime': 1243,
                'maxImageUrl': 'https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/image_audit/prod/1c6b2b3e-795b-48af-9b52-01993a5595e6_fixing_v2.png.webp',
                'pagesnapshottime': '0',
                'isorganic': 'true',
                'pagesnapshot': '{"domainPageArea":[{"viewName":"AppBarLayout","isHidden":false,"isZeroSize":false},{"viewName":"SearchResultHeaderViewRedesign","isHidden":false,"isZeroSize":true},{"viewName":"DcoHorizontalScrollContainerView","isHidden":false,"isZeroSize":false,"viewType":"DYNAMIC_TEMPLATE"},{"viewName":"LegoContainerView","isHidden":false,"isZeroSize":false,"viewType":"U_WIDGET"},{"viewName":"LegoContainerView","isHidden":false,"isZeroSize":false,"viewType":"U_WIDGET"},{"viewName":"TabMenu","isHidden":false,"isZeroSize":false},{"viewName":"BottomNudgingWithCloseButtonView","isHidden":false,"isZeroSize":false}],"domainPageName":"srp"}',
                'preload_image_request': '[{"url":"https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/image_audit/prod/1c6b2b3e-795b-48af-9b52-01993a5595e6_fixing_v2.png.webp","image_loading_start":363271658,"requested_resolution":"-2147483648x-2147483648"},{"url":"https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/3b3a/29bcfec71c7f96c93b580e2df31da837e3779be4f7c74f953bd1d0535197.jpg.webp","image_loading_start":363271659,"requested_resolution":"-2147483648x-2147483648"},{"url":"https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/3b3a/29bcfec71c7f96c93b580e2df31da837e3779be4f7c74f953bd1d0535197.jpg.webp","image_loading_start":363271659,"requested_resolution":"-2147483648x-2147483648"},{"url":"https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/d5bb/1922703ddb30b2e92bdce03dcb318285547c6da0829d86c2cc9198b0dba7.png.webp","image_loading_start":363271659,"requested_resolution":"-2147483648x-2147483648"}]',
                'viewholdertimedetails': '[{"Key":"com.coupang.mobile.commonui.widget.commonlist.viewholder.DefaultCommonViewHolder","ViewHolderCreationTime":0,"ViewHolderDataBindingTime":0},{"Key":"com.coupang.mobile.commonui.widget.commonlist.viewholder.DefaultCommonViewHolder","ViewHolderCreationTime":0,"ViewHolderDataBindingTime":0},{"Key":"com.coupang.mobile.domain.advertising.view.viewholder.DynamicTemplateVHFactoryImpl.VH","ViewHolderCreationTime":1,"ViewHolderDataBindingTime":39},{"Key":"com.coupang.mobile.commonui.rds.renderengine.viewholder.UWidgetViewHolderFactory.UWidgetVH","ViewHolderCreationTime":53,"ViewHolderDataBindingTime":26},{"Key":"com.coupang.mobile.commonui.rds.renderengine.viewholder.UWidgetViewHolderFactory.UWidgetVH","ViewHolderCreationTime":38,"ViewHolderDataBindingTime":12}]',
                'timetotrackviewviewholdertimedetails': '1'
            }
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.102+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 13697,
                'schemaVersion': 2
            },
            'data': {
                'domain': 'SRP',
                'logCategory': 'impression',
                'logType': 'impression',
                'pageName': 'srp',
                'eventName': 'srp_product_unit_exposure',
                'query': '호박식혜 달빛',
                'searchId': '0797993d22350',
                'ixid': '00014a5f-2f79-23fb-e384-abdc292008d4',
                'productIdList': '[9183773210, 9024146312, 9024146312, 9183773210]',
                'itemIdList': '[27087300150, 26462223018, 26462223016, 27087300159]',
                'vendorItemIdList': '[94055536143, 93437504336, 93437504341, 94055536145]',
                'pageStartTime': 363247755,
                'pageEndTime': 363278229,
                'itemStartTime': '[[363271913], [363271913], [363274332], [363274332]]',
                'itemEndTime': '[[363278228], [363278228], [363278228], [363278228]]',
                'endEventType': 'SDP_VID',
                'endItemEventTypeList': '[[SDP_VID], [SDP_VID], [SDP_VID], [SDP_VID]]',
                'vendorItemCount': 4
            },
            'extra': {}
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.108+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 14741,
                'schemaVersion': 36
            },
            'data': {
                'imageCount': '1',
                'premiumCategory': '',
                'isFreeReturn': 'False',
                'isUsedProductInfoVisible': '',
                'searchId': '0797993d22350',
                'optionPicker': '',
                'eligibleLiveBadgeType': '',
                'adIcon': '',
                'hasDisplayMyCcidPrice': '',
                'otLinkLabelText': '',
                'rank': 2,
                'isBestSellingBadgeVisible': '',
                'dynamicPricingValueNudgeType': '',
                'isNoDiscount': 'True',
                'isItemPresentInCart': '',
                'extraAttributes': '',
                'itemId': 26462223018,
                'isTitleTruncated': '',
                'domain': 'srp',
                'viewType': 'BRICK_PRODUCT_UNIT_GRID_UPROTOCOL_M2',
                'isWishlistItem': '',
                'recentlyViewedItem': '',
                'isPageViewNudge': '',
                'brandNameExpression': '',
                'isSocialProofEligibleList': '',
                'ctaGroup': '',
                'vendorItemId': 93437504336,
                'isProductOfferVisible': '',
                'pastPurchasedInfo': '',
                'searchRank': 1,
                'salesPricePrefix': '',
                'hasUspGeneratedByCoupangAi': 'False',
                'hasSocialProof': '',
                'deviceFontScale': '1.0',
                'isProductReviewSurveyVisible': '',
                'isDiscountRateVisible': 'true',
                'hasDiscount': '',
                'hasItemUnitSales': '',
                'isRuleBasedTitleEligible': '',
                'colorCodeAvailable': '',
                'topBrandTooltip': '',
                'brandshopType': '',
                'unitPriceInfo': 'NO VALUE',
                'isBadReferencePrice': 'False',
                'highlightedAttrInTitle': '',
                'ratingCountString': '(1)',
                'displayCcidType': '',
                'priceDropType': '',
                'ccidDiscountAmount': '',
                'pageViewNudgeNumbers': '',
                'isSalesPriceVisible': 'true',
                'vendorId': '',
                'couponNudge': '',
                'source': 'srp',
                'pageName': 'srp',
                'reviewRating': '',
                'hasDeliveryFee': '',
                'visualSearchId': '',
                'isRluxString': '',
                'isSalesPricePrefixVisible': '',
                'feedId': '',
                'socialProofNumUsersString': '',
                'isPageViewNudgeEligible': '',
                'titleMaxNumberOfLines': '2',
                'isNewReleaseDateAttribute': '',
                'productReviewSurvey': '',
                'freebieImage': '',
                'otLinkAttrName': '',
                'availableColorChipType': '',
                'unitname1': 'Beverages',
                'query': '호박식혜 달빛',
                'numberColorChipsVisible': '',
                'unitname2': 'Drinks',
                'vendorName': '',
                'hasDisplayCcidBadge': '',
                'filterKey': '',
                'anchorPrice': 'NO VALUE',
                'reviewSurvey': '',
                'wowPdd': '',
                'isTitleVisible': 'true',
                'isLowestUnitPriceBadge': '',
                'ixid': '00014a5f-2f79-23fb-e384-abdc292008d4',
                'logType': 'impression',
                'isPreviousPurchaseBadge': 'False',
                'midFilterKeys': '',
                'finalPriceV2': 'NO VALUE',
                'displayBestCcidNudge': '',
                'colorHexList': '',
                'hasDisplayCcidPrice': '',
                'discountType': 'NO VALUE',
                'logCategory': 'impression',
                'starRating': 'true',
                'isCouponOfferVisible': '',
                'exposureTimestamp': '2026-01-10T01:31:54.874+0900',
                'otLinkButtonStyle': '',
                'productBenefitGroup': '',
                'isPreviousPurchaseBadgeEligible': 'False',
                'purchaseNudgeNumbers': '',
                'myCcidCcCompany': '',
                'isBadDiscount': 'False',
                'freebieTotalCount': '',
                'bsrBadgeRanking': '',
                'isPurchaseNudge': '',
                'satisfactionNudge': '',
                'interestFreeInstallmentInfo': '',
                'discountRate': 'NO VALUE',
                'isFarfetchString': '',
                'pastPurchaseCountString': '',
                'finalPriceString': '26,990원',
                'brandShopVendorId': '',
                'socialProofNumUsers': '',
                'titleLineCount': '2',
                'isPremiumBrand': '',
                'isRecentViewBadge': 'False',
                'lastMonthPurchaseSPNumUsersStr': '',
                'isSocialProofEligible': '',
                'socialProofNudgeType': '',
                'deliveryLogo': '',
                'deliveryBadge': '',
                'hasSpecSection': '',
                'unitPrice': '(100ml당 675원)',
                'kan3CategoryId': '1449',
                'productId': 9024146312,
                'remoteAreaShippingFeeBadge': 'False',
                'isSocialProofEligibleString': '',
                'highlightedBrandInTitle': '',
                'hasDiscountNudge': '',
                'isPurchaseNudgeEligible': '',
                'brandLink': '',
                'priceDropTargetType': '',
                'subtitle': '',
                'brandId': '',
                'similarProductNudge': '',
                'numAttributeShown': '',
                'ratingAverage': '',
                'rocketMarketType': '',
                'isFarfetch': '',
                'productUnitHeight': '461',
                'rocketDeliveryType': '',
                'attributedTitle': '',
                'colorTextValue': '',
                'productRegionMark': '',
                'dpi': '450',
                'displayedLiveBadgeType': '',
                'originalPriceString': '32,000원',
                'nudge': '',
                'lowStockMessageNumber': 'null',
                'otLinkNumOptions': '',
                'isOriginalPriceVisible': 'true',
                'isPddVisible': 'true',
                'isBestReviewBadge': 'False',
                'brandLinkName': '',
                'modelNumber': '',
                'isBestAwardsBadge': 'False',
                'shortProductRelevance': '',
                'similarProductButton': '',
                'isPromotionBadgeVisible': '',
                'promiseDeliveryDate': '1/13(화) 도착 예정',
                'rating': '',
                'isRecentViewBadgeEligible': 'False',
                'bestAwardsBadgeType': 'N',
                'wowBenefit': '',
                'appliedCcidPrice': '',
                'isPastPurchasedBadge': '',
                'eventName': 'srp_product_unit_impression',
                'isCashOnDelivery': '',
                'clientSessionId': '',
                'freebieVendorItemId': '',
                'lowestUnitPriceBadgeType': '',
                'rocketType': '',
                'highlightedAttrIdInTitle': '',
                'isLowStockMessage': 'False',
                'queryCategory': 'Beverages',
                'isFreshGuaranteeBadgeEligible': '',
                'isBestReviewBadgeEligible': 'False',
                'mobileFlexDeliveryType': '',
                'ratingAverageString': '4.0',
                'isUnitPriceVisible': 'true',
                'tier': '',
                'isPremiumBrandBadge': '',
                'isUnificationBadge': '',
                'pastPurchasedMonth': '',
                'isItemOutOfStock': '',
                'keyAttributes': '',
                'brandShopLevel': '',
                'ratingCount': '',
                'rocketWowType': '',
                'badges': '',
                'discountTimer': '',
                'clickedRelatedKeywords': '',
                'isAiCompPossible': 'False',
                'hasRuleBasedTitle': '',
                'productDeliveryBenefitGroup': '무료배송, • ,오늘출발'
            },
            'extra': {
                'isFashionQuery': 'false',
                'exposedAttributesAvailable': '8개,500ml',
                'similarProduct': 'false',
                'pddMessage': '1/13(화) 도착 예정',
                'abGroups': 'B,C,NOT_APPLICABLE,NOT_APPLICABLE',
                'economicOptionAvailable': 'false',
                'catalogBrandName': '달빛기정떡',
                'hasMultipleImages': 'false',
                'hasSeeMoreOptionsAvailable': 'true',
                'titleExcludeAttributeNames': '8개,500ml',
                'originalTitleStartsWithBrand': 'false',
                'priceInfo': 'anchorPrice:32000,salesPrice:26990,finalPrice:26990,20dMinPrice:null,asisRate:15,tobeRate:0,discountType:noDiscount',
                'sdpThumbnailImageCount': '9',
                'hasLlmBrand': 'true',
                'boldedBrandType': 'LLM',
                'brandInOriginalTitle': 'false',
                'isSamedayDeliveryItem': 'false',
                'isFreeReturnAvailable': 'false',
                'highlightedKeywordsAvailable': '달빛,호박식혜',
                'ratingCount': '(1)',
                'similarProductWidgetShortcut': 'true',
                'finalTitle': '[달빛식혜] 맛있는 국내산 쌀 얼음호박식혜/ 전통 수제 식혜, 8개, 500ml',
                'economicOptionVisible': 'false',
                'isFreeDelivery': 'true',
                'seeMoreOptionAvailable': 'true',
                'seeMoreOptionVisible': 'false',
                'hasWowBenefit': 'false',
                'abTestIds': '88757,96074,94952,86688',
                'originalTitle': '[달빛식혜] 맛있는 국내산 쌀 얼음호박식혜/ 전통 수제 식혜',
                'imageURLs': 'https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/3b3a/29bcfec71c7f96c93b580e2df31da837e3779be4f7c74f953bd1d0535197.jpg.webp',
                'srpThumbnailImageCount': '1',
                'llmRootBrandName': '달빛기정떡',
                'hasCatalogBrand': 'true',
                'isDawnDeliveryItem': 'false',
                'isBrandEqualToProductName': 'false',
                'ratingAverage': '4.0',
                'srpThumbnailImageSize': '187x187',
                'srpThumbnailImageContentSize': '177x187',
                'srpThumbnailImageContainerSize': '192x192',
                'titleContent': '[달빛식혜] 맛있는 국내산 쌀 얼음호박식혜/ 전통 수제 식혜',
                'lengthOfActualTitle': 29,
                'lengthOfVisibleTitle': 29,
                'commonViewType': 'GRID_2',
                'uniqueKey': '5ab1d7b5-d566-4569-90b0-8a5739fbb461:GRID_2',
                'parentViewType': 'LIST'
            }
        },
        {
            'common': {
                'platform': 'android',
                'libraryVersion': '0.6.7',
                'pcid': '17679762746194168937968',
                'lang': 'ko-KR',
                'appCode': 'coupang',
                'market': 'KR',
                'resolution': '1080x2340',
                'eventTime': '2026-01-10T01:31:58.108+0900',
                'memberSrl': '',
                'app': {
                    'osVersion': '15',
                    'model': 'SM-A165N',
                    'appVersionName': '9.0.4',
                    'appVersionCode': 2409040,
                    'uuid': 'f0b740d2-3447-3b2b-b118-d66257275f8f'
                },
                'location': {
                    'region': 'KR',
                    'locale': 'ko-KR',
                    'mcc': '',
                    'timezone': 'Asia/Seoul'
                },
                'appId': 'com.coupang.mobile',
                'appSessionId': '56b36f12-6759-43bb-9077-f7cddcecc13c',
                'systemLanguage': 'ko'
            },
            'meta': {
                'schemaId': 14741,
                'schemaVersion': 36
            },
            'data': {
                'imageCount': '1',
                'premiumCategory': '',
                'isFreeReturn': 'False',
                'isUsedProductInfoVisible': '',
                'searchId': '0797993d22350',
                'optionPicker': '',
                'eligibleLiveBadgeType': '',
                'adIcon': 'true',
                'hasDisplayMyCcidPrice': '',
                'otLinkLabelText': '',
                'rank': 1,
                'isBestSellingBadgeVisible': '',
                'dynamicPricingValueNudgeType': 'lowestpricein7days',
                'isNoDiscount': '',
                'isItemPresentInCart': '',
                'extraAttributes': '',
                'itemId': 27087300150,
                'isTitleTruncated': 'true',
                'domain': 'srp',
                'viewType': 'BRICK_PRODUCT_UNIT_GRID_UPROTOCOL_M2',
                'isWishlistItem': '',
                'recentlyViewedItem': '',
                'isPageViewNudge': '',
                'brandNameExpression': '',
                'isSocialProofEligibleList': '',
                'ctaGroup': '',
                'vendorItemId': 94055536143,
                'isProductOfferVisible': '',
                'pastPurchasedInfo': '',
                'searchRank': 0,
                'salesPricePrefix': '할인',
                'hasUspGeneratedByCoupangAi': 'False',
                'hasSocialProof': '',
                'deviceFontScale': '1.0',
                'isProductReviewSurveyVisible': '',
                'isDiscountRateVisible': '',
                'hasDiscount': 'true',
                'hasItemUnitSales': '',
                'isRuleBasedTitleEligible': '',
                'colorCodeAvailable': '',
                'topBrandTooltip': '',
                'brandshopType': '',
                'unitPriceInfo': 'NO VALUE',
                'isBadReferencePrice': 'False',
                'highlightedAttrInTitle': '',
                'ratingCountString': '(19)',
                'displayCcidType': '',
                'priceDropType': '',
                'ccidDiscountAmount': '',
                'pageViewNudgeNumbers': '',
                'isSalesPriceVisible': 'true',
                'vendorId': '',
                'couponNudge': '',
                'source': 'srp',
                'pageName': 'srp',
                'reviewRating': '',
                'hasDeliveryFee': '',
                'visualSearchId': '',
                'isRluxString': '',
                'isSalesPricePrefixVisible': 'true',
                'feedId': '',
                'socialProofNumUsersString': '',
                'isPageViewNudgeEligible': '',
                'titleMaxNumberOfLines': '2',
                'isNewReleaseDateAttribute': '',
                'productReviewSurvey': '',
                'freebieImage': '',
                'otLinkAttrName': '',
                'availableColorChipType': '',
                'unitname1': 'Beverages',
                'query': '호박식혜 달빛',
                'numberColorChipsVisible': '',
                'unitname2': 'Drinks',
                'vendorName': '',
                'hasDisplayCcidBadge': '',
                'filterKey': '',
                'anchorPrice': 'NO VALUE',
                'reviewSurvey': '',
                'wowPdd': '',
                'isTitleVisible': 'true',
                'isLowestUnitPriceBadge': '',
                'ixid': '00014a5f-2f79-23fb-e384-abdc292008d4',
                'logType': 'impression',
                'isPreviousPurchaseBadge': 'False',
                'midFilterKeys': '',
                'finalPriceV2': 'NO VALUE',
                'displayBestCcidNudge': '',
                'colorHexList': '',
                'hasDisplayCcidPrice': '',
                'discountType': 'NO VALUE',
                'logCategory': 'impression',
                'starRating': 'true',
                'isCouponOfferVisible': '',
                'exposureTimestamp': '2026-01-10T01:31:54.870+0900',
                'otLinkButtonStyle': '',
                'productBenefitGroup': '',
                'isPreviousPurchaseBadgeEligible': 'False',
                'purchaseNudgeNumbers': '',
                'myCcidCcCompany': '',
                'isBadDiscount': '',
                'freebieTotalCount': '',
                'bsrBadgeRanking': '',
                'isPurchaseNudge': '',
                'satisfactionNudge': '',
                'interestFreeInstallmentInfo': '',
                'discountRate': 'NO VALUE',
                'isFarfetchString': '',
                'pastPurchaseCountString': '',
                'finalPriceString': '13,630원',
                'brandShopVendorId': '',
                'socialProofNumUsers': '',
                'titleLineCount': '2',
                'isPremiumBrand': '',
                'isRecentViewBadge': 'False',
                'lastMonthPurchaseSPNumUsersStr': '',
                'isSocialProofEligible': '',
                'socialProofNudgeType': '',
                'deliveryLogo': '',
                'deliveryBadge': '',
                'hasSpecSection': '',
                'unitPrice': '(100ml당 454원)',
                'kan3CategoryId': '1449',
                'productId': 9183773210,
                'remoteAreaShippingFeeBadge': 'False',
                'isSocialProofEligibleString': '',
                'highlightedBrandInTitle': '',
                'hasDiscountNudge': '',
                'isPurchaseNudgeEligible': '',
                'brandLink': '',
                'priceDropTargetType': '',
                'subtitle': '',
                'brandId': '',
                'similarProductNudge': '',
                'numAttributeShown': '',
                'ratingAverage': '',
                'rocketMarketType': '',
                'isFarfetch': '',
                'productUnitHeight': '461',
                'rocketDeliveryType': '',
                'attributedTitle': '',
                'colorTextValue': '',
                'productRegionMark': '',
                'dpi': '450',
                'displayedLiveBadgeType': '',
                'originalPriceString': '23,370원',
                'nudge': '',
                'lowStockMessageNumber': 'null',
                'otLinkNumOptions': '',
                'isOriginalPriceVisible': 'true',
                'isPddVisible': 'true',
                'isBestReviewBadge': 'False',
                'brandLinkName': '',
                'modelNumber': '',
                'isBestAwardsBadge': 'False',
                'shortProductRelevance': '',
                'similarProductButton': '',
                'isPromotionBadgeVisible': '',
                'promiseDeliveryDate': '1/15(목) 도착 예정',
                'rating': '',
                'isRecentViewBadgeEligible': 'False',
                'bestAwardsBadgeType': 'N',
                'wowBenefit': '',
                'appliedCcidPrice': '',
                'isPastPurchasedBadge': '',
                'eventName': 'srp_product_unit_impression',
                'isCashOnDelivery': '',
                'clientSessionId': '',
                'freebieVendorItemId': '',
                'lowestUnitPriceBadgeType': '',
                'rocketType': '',
                'highlightedAttrIdInTitle': '',
                'isLowStockMessage': 'False',
                'queryCategory': 'Beverages',
                'isFreshGuaranteeBadgeEligible': '',
                'isBestReviewBadgeEligible': 'False',
                'mobileFlexDeliveryType': '',
                'ratingAverageString': '5.0',
                'isUnitPriceVisible': 'true',
                'tier': '',
                'isPremiumBrandBadge': '',
                'isUnificationBadge': '',
                'pastPurchasedMonth': '',
                'isItemOutOfStock': '',
                'keyAttributes': '',
                'brandShopLevel': '',
                'ratingCount': '',
                'rocketWowType': '',
                'badges': '',
                'discountTimer': '',
                'clickedRelatedKeywords': '',
                'isAiCompPossible': 'False',
                'hasRuleBasedTitle': '',
                'productDeliveryBenefitGroup': '무료배송'
            },
            'extra': {
                'isFashionQuery': 'false',
                'exposedAttributesAvailable': '6개,500ml',
                'similarProduct': 'false',
                'pddMessage': '1/15(목) 도착 예정',
                'abGroups': 'B,C,NOT_APPLICABLE,NOT_APPLICABLE',
                'economicOptionAvailable': 'false',
                'catalogBrandName': '위아파머스',
                'hasMultipleImages': 'false',
                'titleExcludeAttributeNames': '6개,500ml',
                'originalTitleStartsWithBrand': 'false',
                'priceInfo': 'anchorPrice:23370,salesPrice:18000,finalPrice:13630,20dMinPrice:13770,asisRate:41,tobeRate:1,discountType:goodFinal',
                'sdpThumbnailImageCount': '1',
                'hasLlmBrand': 'false',
                'boldedBrandType': 'Catalog',
                'brandInOriginalTitle': 'false',
                'isSamedayDeliveryItem': 'false',
                'isFreeReturnAvailable': 'false',
                'highlightedKeywordsAvailable': '달빛,호박식혜',
                'ratingCount': '(19)',
                'similarProductWidgetShortcut': 'false',
                'finalTitle': '달빛단호박식혜 국산 단호박 수제식혜 밥알없는식혜 무방부제 무라벨, 6개, 500ml',
                'economicOptionVisible': 'false',
                'isFreeDelivery': 'true',
                'seeMoreOptionAvailable': 'false',
                'seeMoreOptionVisible': 'false',
                'hasWowBenefit': 'false',
                'abTestIds': '88757,96074,94952,86688',
                'originalTitle': '달빛단호박식혜 국산 단호박 수제식혜 밥알없는식혜 무방부제 무라벨',
                'imageURLs': 'https://thumbnail.coupangcdn.com/thumbnails/remote/657x657q90trim/image/vendor_inventory/image_audit/prod/1c6b2b3e-795b-48af-9b52-01993a5595e6_fixing_v2.png.webp',
                'srpThumbnailImageCount': '1',
                'hasCatalogBrand': 'true',
                'isDawnDeliveryItem': 'false',
                'isBrandEqualToProductName': 'false',
                'ratingAverage': '5.0',
                'srpThumbnailImageSize': '187x187',
                'srpThumbnailImageContentSize': '175x187',
                'srpThumbnailImageContainerSize': '192x192',
                'titleContent': '달빛단호박식혜 국산 단호박 수제식혜 밥알없는식혜 무방부제 무라벨',
                'lengthOfActualTitle': 31,
                'lengthOfVisibleTitle': 25,
                'commonViewType': 'GRID_2',
                'uniqueKey': '94057890-8b6b-4fe8-b7ac-b56d0ce23cc6:GRID_2',
                'parentViewType': 'LIST'
            }
        }
    ]
    
    return run_request(session, method, url, headers, body)
